import type { LayoutLoad } from './$types'

// Ensures all pages under this layout (which is all of them) are statically prerendered at build time
export const prerender = true
// If using adapter-static, no index.html is generated by default, which requires some server configuration to work.
// To work around this, the trailingSlash parameter can be set to 'always' to generate index.html files.
// If using adapter-vercel, a config is generated for the redirect from 'page.html' to '/page'.
// export const trailingSlash = 'always'

export const csr = true

export const load: LayoutLoad = async ({ url }) => {
	return {
		baseUrl: url.origin,
	}
}
